name: surf_practice_chat_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  surf_study_jam: ^0.1.0
  cupertino_icons: ^1.0.2

  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  either_dart: ^0.2.0
  injectable: ^1.5.3
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  build_runner: ^2.2.0
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
